### ISSUE TITLE
Configs in .yaml File

### ISSUE THREAD

**Issue by rwer81** [vesoft-inc/nebula-importer#109]
Hello Team, 
When importing csv file with using a  .yaml, if we  state a vertex/edge property without its data type , importer doesn't throw an exception and doesn't do anything. For example:

```
 .....
edge:
        name: friend
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 1
        props:
          - name: startdete
         #### type: timestamp
            index: 2
```
This seems works very well but actually does not. Maybe it should be an error.
Thanks.
