### ISSUE TITLE
 error: Prop index 1 out range 1 of record([847SawUH57a,0.01]))

### ISSUE THREAD

**Issue by defp** [vesoft-inc/nebula-importer#173]
client 
```
./nebula-importer-linux-amd64-v2.6.0
```

the csv example 

```
83Vywxuirk7,6.323
83Vxbbzymnl,1.016
83VxVAtOhlM,3.437
83WIM5lP3IQ,0.01
83WWBWpipQl,0.01
83WdUurhv1A,0.01
83WOl3YKkDQ,0.01
83WWBYAtIXl,0.01
83WykP7jnLE,0.01
83W68p5flDi,1.156
83WcD54qUgd,0.01
```

the Yml config

```
version: v2
description: journal
removeTempFiles: false
clientSettings:
  retry: 3
  concurrency: 2 # number of graph clients
  channelBufferSize: 128
  space: dataengine
  connection:
    user: root
    password: 123456
    address: 192.168.110.149:31883
  postStart:
    commands: |
      UPDATE CONFIGS storage:wal_ttl=3600;
      UPDATE CONFIGS storage:rocksdb_column_family_options = { disable_auto_compactions = true };
    afterPeriod: 8s
  preStop:
    commands: |
      UPDATE CONFIGS storage:rocksdb_column_family_options = { disable_auto_compactions = false };
      UPDATE CONFIGS storage:wal_ttl=86400;
logPath: ./err/t_journal.log
files:
  - path: ./t_journal.csv
    failDataPath: ./err/t_journal.csv
    batchSize: 2000
    type: csv
    csv:
      withHeader: false
      withLabel: false
      delimiter: '|'
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
          type: string
        tags:
          - name: t_journal
            props:
              - name: journal_id
                type: string
                index: 0
              - name: impact_factor
                type: double
                index: 1
```

```
2021/10/29 23:04:24 [ERROR] handler.go:63: Client 0 fail to execute: THERE_ARE_SOME_ERRORS(tag: {0xc000156180 [0xc000142108 0xc000142120]}, error: Prop index 1 out range 1 of record([847SawUH57a,0.01])), ErrMsg: SyntaxError: syntax error near `THERE_ARE_SOME_ERRORS', ErrCode: -1004
```
