### ISSUE TITLE
sequence number of the column in the CSV file doesn't work

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-importer#202]
We are trying to create two edge between two vertices using importer; see the data file at the end.
Can the CSV file column be reversed to create two edges?

```
  - path: ./studentToclassTcode/test.csv
    batchSize: 1000
    inOrder: False
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: STUDENT_HAS_CLASS_TCODE
        withRanking: False
      srcVID:
        type: string
        index: 0
      dstVID:
        type: string
        index: 1
  - path: ./studentToclassTcode/test.csv
    batchSize: 1000
    inOrder: False
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: CLASS_TCODE_HAS_STUDENT
        withRanking: False
      srcVID:
        type: string
        index: 1
      dstVID:
        type: string
        index: 0
```
# TEST.CSV contents
```
009aec0b-0068-16bb-e914-379de14d4e9a,546330
009aec0b-0068-16bb-e914-379de14d4e9a,56139
```

**Comment by wey-gu** [comment]
It generally looks good to me, what's the question/concern here, please?

**Comment by porscheme** [comment]
Same CSV files was used to add undirect edge(s) with column index is reversed; studio does not show two edges.

**Comment by wey-gu** [comment]
Did you also insert vertices for both peer of the edges?

BTW, this is the WIP commit for v3 k8s operator

https://github.com/vesoft-inc/nebula-operator/pull/121

**Comment by veezhang** [comment]
@porscheme So, what is your problem?

**Comment by veezhang** [comment]
@porscheme There looks to be something wrong with the indentation of `srcVID` and `dstVID` in your config file.
So you just find the edge `0->1`.
```
    schema:
      type: edge
      edge:
        name: STUDENT_HAS_CLASS_TCODE
        withRanking: False
        srcVID:
           type: string
          index: 0
        dstVID:
          type: string
          index: 1
```
